import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import { usePrevious } from 'react-use';
import { useCommand, Action } from '../utils/use-command';
import styles from '../styles/Home.module.css'

const testData: Record<string, number>[] = [
  { a: 1, b: 2 },
  { a: 2, b: 4}
];
const Home: NextPage = () => {
  const [counter, setCounter] = useState(0);
  console.log('### counter: ', counter);

  const { data, push, undo } = useCommand<Record<string, number>>(testData);
  console.log('### data: ', data);

  const prevCounter = usePrevious(counter);

  useEffect(() => {
    if (typeof prevCounter === 'number' && prevCounter !== counter) {
      push({
        coordinate: { index: 1, accessor: 'b' },
        action: Action.Insert,
        value: counter,
        reverse: null,
      })
    }
  }, [counter, prevCounter, push]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <button
          onClick={() => setCounter(c => c + 1)}
      >
        <h1 className={styles.title}>
          +1
        </h1>
      </button>

      <button
          onClick={() => undo()}
      >
        <h1 className={styles.title}>
          undo
        </h1>
      </button>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <table className="styled-table">
        <tbody>
        {data.map((row, index) => (
          <tr key={`${index}-row`}>
            <td>a: {row.a}</td>
            <td>b: {row.b}</td>
          </tr>
        ))}
        </tbody>
      </table>
        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
